USE [master]
GO

/****** Object:  Database [Scol]    Script Date: 2/10/2024 3:38:20 AM ******/
CREATE DATABASE [Scol]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Scol', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Scol.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Scol_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Scol_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Scol].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Scol] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Scol] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Scol] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Scol] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Scol] SET ARITHABORT OFF 
GO

ALTER DATABASE [Scol] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Scol] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Scol] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Scol] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Scol] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Scol] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Scol] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Scol] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Scol] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Scol] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Scol] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Scol] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Scol] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Scol] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Scol] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Scol] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Scol] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Scol] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Scol] SET  MULTI_USER 
GO

ALTER DATABASE [Scol] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Scol] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Scol] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Scol] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Scol] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Scol] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Scol] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Scol] SET  READ_WRITE 
GO

